const express = require('express');
const app = express();
const bodyParser = require('body-parser');
app.use(bodyParser.json());
var classRouter = require('./routes/classRoutesApi');
var studentRouter = require('./routes/studentRoutesApi');
var parentRouter = require('./routes/parentDataRoutesApi');
var combinedApi = require('./routes/combinedRoutesApi');
app.use('/',classRouter);
app.use('/',studentRouter);
app.use('/',parentRouter);
app.use('/',combinedApi);
app.listen(4500);